// apps/playground/src/App.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from "vue";
import { EditorCore, EditorUIRenderer } from "@block-editor/editor";
// import '@block-editor/editor/src/styles/index.css' // It is aliased in vite.config.ts

const editorContainer = ref<HTMLElement | null>(null);
let editor: EditorCore | null = null;

onMounted(() => {
  if (editorContainer.value) {
    // 1. Initialize Core
    const core = new EditorCore({
      element: document.createElement("div"), // Internal element for Tiptap
      content:
        "<p>Welcome to the <strong>Block Editor</strong> (Vue Version)! Try selecting text to add a comment.</p>",
    });

    // 2. Initialize UI Renderer
    // This will mount the toolbar, workspace, etc. into our container
    new EditorUIRenderer(core, editorContainer.value);

    editor = core;
  }
});

onBeforeUnmount(() => {
  editor?.destroy();
  if (editorContainer.value) {
    editorContainer.value.innerHTML = "";
  }
});
</script>

<template>
  <div ref="editorContainer" class="app-container"></div>
</template>

<style>
/* Ensure the container takes full height */
.app-container {
  height: 100vh;
  width: 100vw;
  display: flex;
  flex-direction: column;
}

body {
  margin: 0;
  padding: 0;
  font-family:
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
</style>

// apps/playground/src/App.tsx
import { useEffect, useRef, useState } from 'react'
import { EditorCore, EditorUIRenderer, Exporter } from '@block-editor/editor'
// import '@block-editor/editor/dist/index.css'

interface CommentData {
  id: string
  content: string
  date: string
}

function App() {
  const containerRef = useRef<HTMLDivElement>(null)
  const [editorCore, setEditorCore] = useState<EditorCore | null>(null)
  
  useEffect(() => {
    if (!containerRef.current) return

    // Clean up any existing content in the container to prevent double rendering in StrictMode
    containerRef.current.innerHTML = ''

    // 1. Initialize Core
    const core = new EditorCore({
      element: document.createElement('div'), 
      content: '<p>Welcome to the <strong>Block Editor</strong>! Try selecting text to add a comment.</p>',
    })

    // 2. Initialize UI Renderer
    new EditorUIRenderer(core, containerRef.current)

    setEditorCore(core)

    return () => {
      core.destroy()
      // Cleanup DOM on unmount
      if (containerRef.current) {
        containerRef.current.innerHTML = ''
      }
    }
  }, [])

  return (
    <div className="layout" style={{ height: '100vh', width: '100vw' }} ref={containerRef}>
      {/* EditorUIRenderer will mount everything here */}
    </div>
  )
}

export default App
